export interface BlogPost {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  author: string;
  date: string;
  readTime: string;
  featured: boolean;
  body: Array<{ type: "p" | "h" | "quote"; text: string }>;
}

export const BLOG_POSTS: BlogPost[] = [
  {
    id: "b1",
    slug: "what-size-solar-system-does-your-home-need",
    title: "What size solar system does your home actually need?",
    excerpt: "Most Nigerians are sold systems that are either too small (leaving them in the dark after 6pm) or ridiculously oversized. Here's how to get it exactly right.",
    category: "Energy Education",
    author: "Olea Engineering Team",
    date: "May 12, 2026",
    readTime: "6 min",
    featured: true,
    body: [
      { type: "p", text: "The number one mistake people make when going solar in Nigeria is guessing. They hear a neighbor bought a 5KVA inverter and copy. Or they ask a generator dealer who upsells them. The result is either a system that fails by evening, or one that costs three times what they needed." },
      { type: "h", text: "Start with your load, not the inverter size" },
      { type: "p", text: "Before you buy anything, you need a load assessment. Write down every appliance in your home: lights, fans, TVs, fridges, AC units, water pumps, phone chargers. Then find each item's wattage (usually printed on the label or in the manual)." },
      { type: "p", text: "A typical 3-bedroom Lagos home runs about 2,500–3,500W of simultaneous load. That means a 5KVA inverter (which delivers roughly 4,000W continuous) is the right fit — not the 3KVA that's commonly sold as 'enough.'" },
      { type: "quote", text: "Size the battery for how long you want to run, not for what sounds impressive in a sales pitch." },
      { type: "h", text: "How battery capacity translates to real hours" },
      { type: "p", text: "A 200Ah lithium battery at 51.2V stores about 10.24kWh of energy. At a load of 1,500W (a realistic overnight load — fridge, two fans, phone chargers, one TV), you get roughly 6–7 hours. Want 12 hours? You need two batteries." },
      { type: "p", text: "Lead-acid batteries complicate this because you can only safely use 50% of their capacity. A 200Ah lead-acid battery effectively gives you 100Ah of usable power. Lithium gives you 90–95%. That's why lithium wins for anyone who wants reliability." },
      { type: "h", text: "Solar panels: more is almost always better" },
      { type: "p", text: "Your panels need to do two jobs: power your load during the day AND recharge your batteries before nightfall. A common mistake is under-paneling — buying a great inverter and battery but only 2 panels, which means the battery never fully charges." },
      { type: "p", text: "For a 5KVA system with a 200Ah lithium battery, you want at least 6 × 450W panels (2,700W of solar). That gives you enough generation in 5 peak sun hours to cover daytime load and fully recharge overnight consumption." },
      { type: "quote", text: "Nigeria averages 5.5 peak sun hours per day. That's a massive advantage. Don't waste it with undersized panels." },
      { type: "h", text: "The honest cost breakdown (2026)" },
      { type: "p", text: "A properly sized 3-bedroom home system — 5KVA hybrid inverter, 6 × 450W panels, 1 × 200Ah lithium battery, mounting, wiring, and professional installation — runs between ₦1.4M and ₦1.8M. That sounds like a lot until you compare it to ₦80,000/month in diesel plus generator maintenance." },
      { type: "p", text: "At ₦80,000/month, that's ₦960,000/year on diesel alone. Your solar system pays for itself in 18–22 months. After that, your energy is free for the next 20+ years." },
    ],
  },
  {
    id: "b2",
    slug: "inside-a-50kva-install-at-a-lagos-factory",
    title: "Inside a 50KVA install at a Lagos factory",
    excerpt: "How we took a textile factory in Mushin from 12 hours of daily generator downtime to zero — and cut their energy costs by 68% in the first month.",
    category: "Installation Stories",
    author: "Olea Field Team",
    date: "Apr 28, 2026",
    readTime: "8 min",
    featured: false,
    body: [
      { type: "p", text: "In January 2026, we got a call from the operations manager of a mid-sized textile factory in Mushin, Lagos. They were running three 20KVA diesel generators 24/7, burning through ₦2.1M in fuel every month. Maintenance costs, generator breakdowns, and production halts were costing them another ₦400,000/month in lost output." },
      { type: "h", text: "The assessment: understanding a factory's power profile" },
      { type: "p", text: "Industrial assessments are different from home assessments. You're not just counting appliances — you're analyzing three-phase loads, motor startup currents, power factor, harmonic distortion, and peak demand windows." },
      { type: "p", text: "This factory's peak load hit 45KW during the 8–12am production window when all looms were running simultaneously. Off-peak (nights and weekends) dropped to about 8KW for security lighting and cold storage." },
      { type: "quote", text: "The goal wasn't just to replace diesel. It was to build an energy infrastructure that could grow with the factory for the next 25 years." },
      { type: "h", text: "The system design: three-phase hybrid at scale" },
      { type: "p", text: "We installed three 10KVA three-phase hybrid inverters configured in parallel for a combined 30KW continuous output (50KVA peak capacity). Solar array: 80 × 450W panels across the factory roof, totalling 36,000W of generation. Battery bank: 8 × 200Ah lithium batteries in a dedicated battery room, providing 82kWh of storage." },
      { type: "p", text: "The system feeds directly into the factory's existing distribution board. The inverters handle grid presence detection — when NEPA power is available, it supplements. When it disappears (as it does 12–18 hours daily in that area), the system continues without interruption. Zero transfer time." },
      { type: "h", text: "Month 1 results" },
      { type: "p", text: "Diesel consumption dropped from ₦2.1M/month to ₦680,000/month — a 68% reduction. The remaining diesel spend covers two weekend afternoons when cloud cover and high load demand the generators for backup. The factory has had zero unplanned production halts since commissioning." },
      { type: "p", text: "Total system cost: ₦22.4M installed. Payback period at current fuel prices: 9.2 months. Expected system life: 25 years." },
    ],
  },
  {
    id: "b3",
    slug: "lithium-vs-lead-acid-2026-buyers-guide",
    title: "Lithium vs. lead-acid: a 2026 buyer's guide",
    excerpt: "Lead-acid is cheaper upfront. Lithium wins on every other metric. We break down the real numbers so you can make a decision you won't regret in two years.",
    category: "Tech & Innovation",
    author: "Olea Engineering Team",
    date: "Apr 14, 2026",
    readTime: "5 min",
    featured: false,
    body: [
      { type: "p", text: "In 2022, we were installing roughly 60% lead-acid, 40% lithium. In 2026, that ratio has almost reversed. The price gap between the two technologies has narrowed, and the performance difference has become impossible to ignore." },
      { type: "h", text: "The upfront cost gap is shrinking fast" },
      { type: "p", text: "A 200Ah lead-acid battery costs approximately ₦120,000–₦160,000. The equivalent lithium LiFePO4 battery costs ₦580,000–₦680,000. On paper, that's a 4× premium. But the comparison is misleading for two reasons." },
      { type: "p", text: "First, usable capacity: lead-acid is only safely dischargeable to 50%. Lithium goes to 90–95%. So a 200Ah lead-acid effectively gives you 100Ah of usable energy. You need two lead-acid batteries to match one lithium battery's real output. Now the cost ratio is 2× not 4×." },
      { type: "quote", text: "Lead-acid lasts 300–500 cycles. Lithium lasts 6,000+. At one cycle per day, that's 1.5 years vs. 16 years." },
      { type: "h", text: "Cycle life: the number that changes everything" },
      { type: "p", text: "At one full charge/discharge cycle per day (normal for a home solar system), a lead-acid battery needs replacement in 18–24 months. Lithium lasts 15–20 years — essentially the lifetime of your solar panels." },
      { type: "p", text: "Over 10 years, a lead-acid setup requires 4–5 battery replacements. At ₦240,000 per 200Ah pair, that's ₦960,000–₦1.2M in battery costs alone over a decade. One lithium battery at ₦620,000 covers the same period with money left over." },
      { type: "h", text: "Performance differences that matter day-to-day" },
      { type: "p", text: "Lithium charges faster — a 200Ah LiFePO4 reaches full charge in 2–3 hours from solar. Lead-acid takes 6–8 hours and slows dramatically in the final 20% (the absorption phase). In Nigerian conditions where peak sun is limited to 5–6 hours, faster charging means more usable energy every day." },
      { type: "p", text: "Lead-acid also loses capacity in heat. In Lagos or Abuja, where battery enclosures regularly reach 35–40°C, lead-acid batteries degrade 20–30% faster than their rated specs. Lithium is stable up to 60°C." },
      { type: "h", text: "Our recommendation" },
      { type: "p", text: "If you're on a very tight budget and replacing the battery every 2 years is acceptable, lead-acid is still an option. For everyone else — and especially for anyone building a system they expect to last — lithium LiFePO4 is the only sensible choice. It's what we install in every Olea system." },
    ],
  },
  {
    id: "b4",
    slug: "five-signs-your-generator-is-costing-you-more",
    title: "Five signs your generator is costing you more than you think",
    excerpt: "Diesel is only the headline cost. The real bill hides in maintenance, downtime, and the things you stopped doing because the power wasn't reliable.",
    category: "Energy Education",
    author: "Olea Team",
    date: "Mar 30, 2026",
    readTime: "5 min",
    featured: false,
    body: [
      { type: "p", text: "A generator feels cheap because you bought it once and you pay for the fuel in small, forgettable amounts. But add it all up over a year and the number shocks most people. Here are five costs worth counting honestly." },
      { type: "h", text: "1. The fuel you track — and the fuel you forget" },
      { type: "p", text: "Most business owners who run a generator know their monthly diesel bill. What they don't track is the fuel wasted idling at low load, the extra diesel consumed when the engine is dirty or poorly maintained, or the cost of sourcing fuel during scarcity when black-market prices surge 40–60%." },
      { type: "p", text: "A 10KVA generator running 10 hours/day burns roughly 40–50 litres of diesel. At ₦1,400/litre, that's ₦56,000–₦70,000 per day. Per month: ₦1.7M–₦2.1M. Most business owners mentally anchor to the lower number and forget the variation." },
      { type: "quote", text: "Fuel is the cost you see. Downtime is the cost you feel. Maintenance is the cost you defer until it becomes an emergency." },
      { type: "h", text: "2. Maintenance you postpone" },
      { type: "p", text: "A generator needs an oil change every 250–300 operating hours. At 10 hours/day, that's every 25–30 days. Most small business owners skip cycles when cash is tight. The result is engine wear that shortens the generator's life from 10 years to 4–5 years — and a catastrophic breakdown at the worst possible moment." },
      { type: "h", text: "3. Lost revenue during downtime" },
      { type: "p", text: "The generator is never reliable in the way electricity should be. It trips, runs out of fuel, overheats. Every hour of unplanned downtime has a cost. For a hair salon, it's lost clients. For a cold store, it's spoiled goods. For a printing business, it's a missed deadline. Most operators never add this number to their energy bill, but it's often the largest cost." },
      { type: "h", text: "4. The noise and health tax" },
      { type: "p", text: "Diesel generators run at 70–90dB. Sustained exposure above 70dB causes hearing damage over time. Diesel exhaust fumes contain particulates, carbon monoxide, and nitrogen oxides linked to respiratory disease. Your staff absorbs these costs in ways that eventually show up in sick days, turnover, and healthcare costs." },
      { type: "h", text: "5. The opportunity cost of constrained hours" },
      { type: "p", text: "How many businesses in Nigeria close at 6pm not because there are no customers, but because running the generator for evening hours isn't worth the cost? Solar with battery storage doesn't just cut your energy bill — it removes the cap on your operating hours. Some of our clients increased monthly revenue by 20–35% simply by being able to serve customers after dark." },
    ],
  },
  {
    id: "b5",
    slug: "how-solar-pays-for-itself-the-real-numbers",
    title: "How solar pays for itself: the real numbers",
    excerpt: "Solar isn't a cost. It's a prepayment on decades of free power. Here's exactly how the payback works, with real Olea client numbers.",
    category: "Energy Education",
    author: "Olea Engineering Team",
    date: "Mar 16, 2026",
    readTime: "6 min",
    featured: false,
    body: [
      { type: "p", text: "The biggest myth about solar is that it's expensive. It has an upfront price, yes, but unlike diesel, you pay it once, and then the fuel is free for decades. The right way to think about solar is as buying years of electricity in advance, at a discount." },
      { type: "h", text: "The payback period explained simply" },
      { type: "p", text: "A typical 5KVA home system installed by Olea runs ₦1.4M–₦1.8M. The same homeowner spending ₦80,000/month on diesel and generator maintenance spends ₦960,000/year. Divide the system cost by annual savings: payback in 18–22 months." },
      { type: "p", text: "After payback, the remaining 18–23 years of panel life produce effectively free electricity. Over 20 years, that's ₦960,000 × 20 = ₦19.2M of avoided diesel costs — against a one-time ₦1.6M investment. That's a 12× return." },
      { type: "quote", text: "The question isn't whether you can afford solar. It's whether you can afford to keep paying for diesel." },
      { type: "h", text: "Why fuel price inflation makes solar even smarter" },
      { type: "p", text: "Diesel in Nigeria cost ₦400/litre in 2022. By 2026 it's ₦1,400/litre — a 250% increase in four years. Your solar payback calculation should account for the fact that whatever diesel costs today, it will almost certainly cost more in year 3, year 5, and year 10. Solar locks in your energy cost at the day of installation." },
      { type: "h", text: "Real client examples from 2025–2026" },
      { type: "p", text: "Emmanuel O., factory owner in Lagos: Spent ₦450,000/month on diesel. Installed a ₦22M industrial system in March 2025. First month's diesel bill: ₦68,000. System pays back in 4.2 years. Expected 20-year fuel savings: ₦107M." },
      { type: "p", text: "Blessing A., supermarket in Port Harcourt: Refrigeration systems cost ₦80,000/month in diesel. Installed a ₦6.5M system. Monthly fuel cost now: ₦7,200. Payback in 6.8 months. The supermarket now stays open 2 hours later each evening, generating additional monthly revenue that wasn't previously possible." },
      { type: "h", text: "The factors that change the calculation" },
      { type: "p", text: "Payback period varies based on how much you currently spend on diesel (the higher, the faster), your load profile (steady daytime loads benefit most), your location (sunlight hours vary from 4.5 in the south to 6+ in the north), and your system quality. Cheap inverters and low-grade panels produce less, degrade faster, and quietly extend payback beyond projections. Olea only installs vetted Tier-1 equipment with real warranties." },
    ],
  },
  {
    id: "b6",
    slug: "solar-maintenance-guide-nigeria",
    title: "Keeping your system healthy: a simple maintenance guide",
    excerpt: "Solar is famously low-maintenance, but 'low' isn't 'none.' A few simple habits keep your system performing at its peak for decades.",
    category: "Tech & Innovation",
    author: "Olea Engineering Team",
    date: "Feb 28, 2026",
    readTime: "4 min",
    featured: false,
    body: [
      { type: "p", text: "One of the biggest selling points of solar over diesel generators is how little maintenance it needs. No oil changes. No filter replacements. No engine servicing. But 'low maintenance' doesn't mean 'no maintenance', and the habits that protect your system are simple and quick." },
      { type: "h", text: "Panel cleaning: more important than you think in Nigeria" },
      { type: "p", text: "Dust accumulation on solar panels is the number one cause of generation losses in Nigeria. Harmattan season is particularly severe — a heavy dust layer can reduce panel output by 15–25%. In coastal areas, salt deposits cause similar losses. Clean panels every 4–6 weeks during dry season, and after any Harmattan dust event." },
      { type: "p", text: "Use clean water and a soft cloth or sponge. Clean in the morning before the panels heat up (a wet sponge on a 60°C panel can crack the glass). Never use abrasive materials or chemical solvents. A 30-minute clean every month can recover hundreds of naira in daily generation." },
      { type: "quote", text: "Dust-covered panels don't announce themselves. Check yours today — you might be surprised." },
      { type: "h", text: "Battery health checks" },
      { type: "p", text: "For lithium batteries (LiFePO4), the monitoring app is your primary health tool. Watch for: the battery consistently failing to reach 100% by early afternoon (a sign of panel under-supply or battery degradation), faster-than-expected discharge overnight (a sign of a faulty cell or excessive load), and error codes or temperature warnings from the BMS." },
      { type: "p", text: "Keep the battery enclosure ventilated and away from direct heat sources. LiFePO4 tolerates heat better than lead-acid, but sustained temperatures above 45°C accelerate degradation. In unconditioned spaces during peak summer, consider adding a small ventilation fan." },
      { type: "h", text: "Annual professional inspection" },
      { type: "p", text: "Once a year, have a qualified technician inspect your system. The key checks: DC cable connections for corrosion or loosening, mounting bracket integrity (especially after wind season), inverter firmware updates, and a full system output test to compare against commissioning data. Olea offers annual maintenance contracts that include all of the above plus priority response for any issues." },
    ],
  },
  {
    id: "b7",
    slug: "how-we-powered-a-clinic-network-ogun-state",
    title: "How we powered a 12-clinic network in Ogun State",
    excerpt: "Healthcare facilities can't afford power cuts. Here's how we designed and installed a solar solution across 12 rural clinics — each with different loads, locations, and constraints.",
    category: "Installation Stories",
    author: "Olea Field Team",
    date: "Feb 12, 2026",
    readTime: "7 min",
    featured: false,
    body: [
      { type: "p", text: "In late 2025, we were approached by a healthcare NGO operating 12 primary healthcare clinics across Ogun State. Each clinic ran on diesel generators for between 8 and 14 hours daily. Combined monthly fuel spend: ₦3.8M. More critically, six of the clinics had experienced power failures during procedures or vaccine cold-chain breaks in the previous year alone." },
      { type: "h", text: "The challenge: 12 sites, 12 different problems" },
      { type: "p", text: "No two clinics were identical. One had a small maternity ward running ventilators and surgical lights. Another was a basic outpatient facility with a refrigerator for vaccines, lights, and fans. Three were in areas with reasonable grid access; the remaining nine had NEPA supply less than 2 hours per day on average." },
      { type: "p", text: "We conducted individual load assessments and solar surveys at each site, measuring roof orientation, shading, existing wiring quality, and local weather data. The result was 12 different system designs — not a copy-paste approach." },
      { type: "quote", text: "Healthcare power isn't about convenience. It's about what happens to a patient when the lights go out mid-procedure. We designed every system with that in mind." },
      { type: "h", text: "System specs across the network" },
      { type: "p", text: "The smallest installation (a 2-room outpatient clinic): 3KVA hybrid inverter, 6 × 450W panels, 1 × 200Ah lithium battery. Covers lights, fans, vaccine fridge, and charging station. The largest (the maternity facility): 10KVA three-phase hybrid, 20 × 450W panels, 4 × 200Ah lithium batteries. Supports surgical lights, ventilator, autoclave, refrigeration, and staff quarters." },
      { type: "h", text: "Results after 90 days" },
      { type: "p", text: "Combined diesel spend across the 12 clinics: ₦440,000/month — an 88% reduction from ₦3.8M. Zero power interruptions during medical procedures across the network. All vaccine cold chains maintained continuously. Two clinics that previously closed at 5pm (when generator costs made evening operation uneconomical) now operate until 9pm, serving an additional 40–60 patients per day." },
      { type: "p", text: "Total project value: ₦87M across 12 sites. Average payback per site: 11 months. The NGO is now planning phase 2 — 8 more clinics in Oyo and Ekiti States." },
    ],
  },
  {
    id: "b8",
    slug: "smart-energy-monitoring-nigeria",
    title: "How smart energy monitoring works (and why you want it)",
    excerpt: "Knowing your system is running isn't enough. Real-time monitoring tells you when to run heavy appliances, when clouds reduce generation, and when something needs attention.",
    category: "Tech & Innovation",
    author: "Olea Engineering Team",
    date: "Jan 28, 2026",
    readTime: "4 min",
    featured: false,
    body: [
      { type: "p", text: "Every Olea hybrid inverter comes with WiFi monitoring built in. Most of our clients set it up once and check it every morning like they check the weather. Once you can see your energy in real time, you start making smarter decisions automatically." },
      { type: "h", text: "What the monitoring dashboard shows you" },
      { type: "p", text: "The app shows five key metrics in real time: solar generation (kW currently being produced), load consumption (how much your home or business is currently using), battery state of charge (%), grid import/export, and a 30-day history of all four." },
      { type: "p", text: "That history is where the real insights live. You can see which days cloud cover hit your generation, which afternoons your load spiked (usually when someone turned on an AC), and how your battery holds overnight through the week." },
      { type: "quote", text: "Clients who use the monitoring app report 15–25% lower energy consumption within the first month, just from seeing the data." },
      { type: "h", text: "Smarter decisions you'll make automatically" },
      { type: "p", text: "Once you know your system generates peak power between 10am and 2pm, you'll naturally shift heavy loads — washing machine, electric water heater, charging power banks — to that window. You're using free solar power instead of drawing from the battery or grid." },
      { type: "p", text: "The app also sends alerts. If your generation drops unexpectedly (a panel is shaded or dusty), you get notified. If your battery doesn't reach full charge by afternoon, the system flags it so you can reduce evening load. These early warnings prevent costly surprises." },
      { type: "h", text: "Remote monitoring for businesses with multiple sites" },
      { type: "p", text: "For business owners with multiple locations — a chain of pharmacies, a group of schools, a hotel brand — the monitoring platform aggregates all sites in one dashboard. You can compare generation efficiency across locations, spot which sites have dust issues, and schedule maintenance proactively rather than reactively. We've had clients identify a failing panel string at a branch they haven't visited in months, purely from the monitoring data." },
    ],
  },
  {
    id: "b9",
    slug: "solar-for-schools-nigeria",
    title: "Why schools in Nigeria are switching to solar — and what it costs",
    excerpt: "From primary schools in Owerri to universities in Abuja — clean energy is giving Nigerian schools stable power for computers, labs, and lights at a fraction of diesel costs.",
    category: "Energy Education",
    author: "Olea Engineering Team",
    date: "Jan 14, 2026",
    readTime: "5 min",
    featured: false,
    body: [
      { type: "p", text: "A secondary school principal in Owerri told us something that stuck: 'We've been buying diesel for 14 years. It never gets cheaper. It never becomes reliable. We just keep buying it.' She was spending ₦580,000/month fueling generators to power lights, fans, and the one computer lab they had." },
      { type: "h", text: "What a school solar system looks like" },
      { type: "p", text: "Schools have a profile that suits solar extremely well. Their peak usage — classrooms running during the day — coincides exactly with peak solar generation hours. Unlike homes, they don't need heavy overnight storage because most of the demand is daytime." },
      { type: "p", text: "A typical secondary school setup at Olea: 10KVA hybrid inverter, 16 × 450W panels (7,200W array), 2 × 200Ah lithium batteries. This powers all classrooms, the admin block, and a computer lab with reliable power 8 hours per day." },
      { type: "quote", text: "The school doesn't need to store much energy — they just need the sun to power school hours. And Nigeria has more than enough sun." },
      { type: "h", text: "Typical cost and payback for a school" },
      { type: "p", text: "An installation like the one above runs approximately ₦4.2M–₦5.8M fully installed, depending on site conditions and cable runs. At ₦580,000/month in diesel savings, payback is 7–10 months." },
      { type: "p", text: "Beyond the economics, schools gain something harder to price: reliability. Exams no longer depend on NEPA. Computer classes run on schedule. Science labs with sensitive equipment stop suffering from voltage fluctuations that destroy equipment." },
    ],
  },
  {
    id: "b10",
    slug: "solar-warranties-what-to-ask",
    title: "Solar warranties: what's actually covered and what to ask",
    excerpt: "A 25-year panel warranty sounds reassuring until you read the fine print. Here's what the numbers mean and the four questions to ask any solar company before you sign.",
    category: "Tech & Innovation",
    author: "Olea Engineering Team",
    date: "Dec 30, 2025",
    readTime: "5 min",
    featured: false,
    body: [
      { type: "p", text: "Solar warranties sound simple: 25 years on panels, 10 years on inverters. But the details inside those warranties determine whether the number means anything when something actually goes wrong. Here's how to read them honestly." },
      { type: "h", text: "Two different panel warranties" },
      { type: "p", text: "Every solar panel comes with two separate warranties. The product warranty (usually 10–12 years) covers physical defects — cracked glass, delamination, frame failure. The performance warranty (usually 25 years) guarantees the panel will still produce a certain percentage of its rated output after 25 years — typically 80–87% for Tier-1 panels." },
      { type: "p", text: "The performance warranty is where cheap panels fail. A Tier-1 panel might guarantee 87% output at year 25. A no-name brand might guarantee only 70% — meaning after a quarter century, it's producing barely 70% of what you paid for. Over 25 years, that difference is significant." },
      { type: "quote", text: "A warranty is only as good as the company standing behind it. Ask: will this manufacturer still exist in 15 years?" },
      { type: "h", text: "Inverter warranties and what they cover" },
      { type: "p", text: "Most hybrid inverters come with a 5-year product warranty, extendable to 10 years. The warranty typically covers manufacturing defects and component failure. It usually does not cover damage from lightning strikes, flooding, physical impact, or installation errors. This is why professional installation with a surge protection device isn't optional." },
      { type: "h", text: "Four questions to ask your solar installer" },
      { type: "p", text: "1. Can you show me the warranty documents (not just a verbal promise)? 2. What is the local warranty claim process — will I get a replacement unit or wait months for factory inspection? 3. Is the installer's labor warranty separate from the product warranty, and how long does it last? 4. Do you carry the spare parts for this inverter model in Nigeria, or must parts be imported? A reputable company answers all four confidently. At Olea, our warranty support is handled by our local team, not routed through international distributors." },
      { type: "h", text: "The Olea warranty promise" },
      { type: "p", text: "Every Olea installation comes with a 2-year full labor warranty, 12-year product warranty on all panels (Tier-1 brands only), 5-year inverter warranty with local claim resolution, and a dedicated support contact who responds within 2 business hours. We don't disappear after installation — that's the Olea guarantee." },
    ],
  },
];

export function getBlogPostBySlug(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find((p) => p.slug === slug);
}

export function getRelatedPosts(currentId: string, limit = 3): BlogPost[] {
  const current = BLOG_POSTS.find((p) => p.id === currentId);
  if (!current) return BLOG_POSTS.filter((p) => p.id !== currentId).slice(0, limit);
  const sameCategory = BLOG_POSTS.filter((p) => p.id !== currentId && p.category === current.category);
  const others = BLOG_POSTS.filter((p) => p.id !== currentId && p.category !== current.category);
  return [...sameCategory, ...others].slice(0, limit);
}
