import type { Product } from "@/types";

export const SEED_PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "5KVA Hybrid Inverter",
    slug: "5kva-hybrid-inverter",
    description: "A high-performance hybrid inverter designed for Nigerian conditions. Handles both grid and battery power with seamless switching. Supports solar input up to 5,000W and delivers pure sine wave output suitable for sensitive electronics.",
    shortDescription: "Pure sine wave · grid + battery · solar ready",
    price: 280000,
    compareAtPrice: 320000,
    stockQuantity: 12,
    lowStockThreshold: 3,
    category: "inverters",
    brand: "Olea Select",
    images: [],
    specifications: {
      "Rated Power": "5KVA / 4,000W",
      "Input Voltage": "48V DC",
      "Output Voltage": "220V AC ±5%",
      "Battery Type": "Lithium / Lead-Acid",
      "Solar Input": "Up to 5,000W",
      "Efficiency": "≥93%",
      "Waveform": "Pure Sine Wave",
      "Dimensions": "560 × 290 × 155mm",
      "Weight": "18kg",
      "Warranty": "2 years",
    },
    isActive: true,
    isFeatured: true,
    requiresInstallation: true,
    rating: 5,
    reviewCount: 42,
    createdAt: new Date("2026-01-10"),
    updatedAt: new Date("2026-03-15"),
  },
  {
    id: "p2",
    name: "450W Mono Solar Panel",
    slug: "450w-mono-solar-panel",
    description: "Tier-1 monocrystalline solar panel with 25-year performance warranty. High efficiency cells deliver maximum output even in diffuse light — ideal for Lagos, Abuja, and the broader Nigerian climate.",
    shortDescription: "Tier-1 monocrystalline · 25yr warranty · high efficiency",
    price: 95000,
    stockQuantity: 4,
    lowStockThreshold: 5,
    category: "solar_panels",
    brand: "Olea Select",
    images: [],
    specifications: {
      "Peak Power": "450W",
      "Cell Type": "Monocrystalline PERC",
      "Efficiency": "21.3%",
      "Open Circuit Voltage": "49.2V",
      "Short Circuit Current": "11.6A",
      "Operating Temperature": "-40°C to +85°C",
      "Dimensions": "2094 × 1038 × 35mm",
      "Weight": "21.5kg",
      "Warranty": "25 years performance",
    },
    isActive: true,
    isFeatured: true,
    requiresInstallation: false,
    rating: 4,
    reviewCount: 28,
    createdAt: new Date("2026-01-10"),
    updatedAt: new Date("2026-03-15"),
  },
  {
    id: "p3",
    name: "200Ah Lithium Battery",
    slug: "200ah-lithium-battery",
    description: "LiFePO4 lithium battery with 6,000+ cycle life — that's 15–20 years of daily use. Built-in BMS protects against overcharge, over-discharge, and short circuits. The smartest long-term investment in your energy system.",
    shortDescription: "LiFePO4 · 6,000+ cycles · built-in BMS",
    price: 620000,
    stockQuantity: 8,
    lowStockThreshold: 2,
    category: "batteries",
    brand: "Olea Select",
    images: [],
    specifications: {
      "Capacity": "200Ah / 10.24kWh",
      "Chemistry": "LiFePO4",
      "Nominal Voltage": "51.2V",
      "Cycle Life": "6,000+ cycles",
      "Charge Voltage": "58.4V",
      "Max Charge Current": "100A",
      "Max Discharge Current": "200A",
      "Operating Temp": "0°C to +55°C",
      "Weight": "48kg",
      "Warranty": "5 years",
    },
    isActive: true,
    isFeatured: true,
    requiresInstallation: false,
    rating: 5,
    reviewCount: 61,
    createdAt: new Date("2026-01-10"),
    updatedAt: new Date("2026-03-15"),
  },
  {
    id: "p4",
    name: "3.5KVA Complete Home System",
    slug: "3-5kva-complete-home-system",
    description: "Everything you need to power a 3–4 bedroom home, professionally installed by our engineers. Includes hybrid inverter, solar panels, lithium batteries, mounting hardware, wiring, and commissioning. One price. Zero stress.",
    shortDescription: "Complete home kit · installation included · monitored",
    price: 1450000,
    stockQuantity: 3,
    lowStockThreshold: 1,
    category: "systems",
    brand: "Olea Technologies",
    images: [],
    specifications: {
      "Inverter": "3.5KVA Hybrid",
      "Solar Panels": "6 × 450W",
      "Battery": "2 × 200Ah LiFePO4",
      "Total Solar": "2,700W",
      "Battery Storage": "20.48kWh",
      "Daily Output": "~12–16kWh",
      "Installation": "Included",
      "Monitoring": "WiFi app included",
      "Warranty": "System: 2yr / Panels: 25yr",
    },
    isActive: true,
    isFeatured: true,
    requiresInstallation: true,
    rating: 5,
    reviewCount: 19,
    createdAt: new Date("2026-01-10"),
    updatedAt: new Date("2026-03-15"),
  },
  {
    id: "p5",
    name: "MPPT 60A Charge Controller",
    slug: "mppt-60a-charge-controller",
    description: "Maximum Power Point Tracking controller that squeezes every watt from your panels. Up to 30% more efficient than PWM controllers. Compatible with 12V, 24V, and 48V battery banks.",
    shortDescription: "Max power point tracking · 12/24/48V · LCD display",
    price: 78000,
    stockQuantity: 20,
    lowStockThreshold: 5,
    category: "charge_controllers",
    brand: "Olea Select",
    images: [],
    specifications: {
      "Rated Current": "60A",
      "Max PV Open Circuit": "150V",
      "Battery Voltage": "12/24/48V auto",
      "Max PV Input Power": "780W (12V) / 1560W (24V) / 3120W (48V)",
      "Efficiency": "≥98%",
      "Display": "LCD backlit",
      "Dimensions": "165 × 112 × 52mm",
      "Weight": "0.78kg",
      "Warranty": "1 year",
    },
    isActive: true,
    isFeatured: false,
    requiresInstallation: false,
    rating: 4,
    reviewCount: 33,
    createdAt: new Date("2026-02-01"),
    updatedAt: new Date("2026-03-15"),
  },
  {
    id: "p6",
    name: "10KVA Industrial Inverter",
    slug: "10kva-industrial-inverter",
    description: "Three-phase industrial grade inverter built for factories, warehouses, and commercial facilities. Handles heavy motor loads with ease. Remote monitoring via WiFi and RS485.",
    shortDescription: "Three-phase · factory grade · WiFi monitoring",
    price: 980000,
    stockQuantity: 2,
    lowStockThreshold: 1,
    category: "inverters",
    brand: "Olea Select",
    images: [],
    specifications: {
      "Rated Power": "10KVA / 8,000W",
      "Phase": "Three-phase output",
      "Input Voltage": "192V DC (4 × 48V)",
      "Output Voltage": "380V AC (3-phase)",
      "Solar Input": "Up to 10,000W",
      "Efficiency": "≥94%",
      "Waveform": "Pure Sine Wave",
      "Communication": "WiFi + RS485",
      "Warranty": "2 years",
    },
    isActive: true,
    isFeatured: false,
    requiresInstallation: true,
    rating: 5,
    reviewCount: 7,
    createdAt: new Date("2026-02-01"),
    updatedAt: new Date("2026-03-15"),
  },
  {
    id: "p7",
    name: "300W Poly Solar Panel",
    slug: "300w-poly-solar-panel",
    description: "Reliable polycrystalline panel for budget-conscious installations. A solid performer for rural and off-grid setups where cost per watt matters more than footprint.",
    shortDescription: "Budget-friendly · reliable · off-grid ready",
    price: 62000,
    stockQuantity: 0,
    lowStockThreshold: 5,
    category: "solar_panels",
    brand: "Olea Select",
    images: [],
    specifications: {
      "Peak Power": "300W",
      "Cell Type": "Polycrystalline",
      "Efficiency": "16.5%",
      "Open Circuit Voltage": "45.8V",
      "Dimensions": "1956 × 992 × 40mm",
      "Weight": "18kg",
      "Warranty": "10 years performance",
    },
    isActive: true,
    isFeatured: false,
    requiresInstallation: false,
    rating: 4,
    reviewCount: 15,
    createdAt: new Date("2026-02-10"),
    updatedAt: new Date("2026-03-15"),
  },
  {
    id: "p8",
    name: "Aluminum Mounting Rail Kit",
    slug: "aluminum-mounting-rail-kit",
    description: "Heavy-duty aluminum mounting rails for rooftop solar panel installation. Corrosion-resistant, pre-drilled, compatible with all standard panel sizes. Includes mid and end clamps.",
    shortDescription: "Aluminum · 6m × 4 rails · clamps included",
    price: 35000,
    stockQuantity: 50,
    lowStockThreshold: 10,
    category: "accessories",
    brand: "Olea Select",
    images: [],
    specifications: {
      "Material": "Anodized Aluminum",
      "Rail Length": "6m per rail",
      "Quantity": "4 rails per set",
      "Compatible": "All standard panels",
      "Includes": "Mid clamps, end clamps, T-bolts",
      "Load Rating": "Up to 480kg distributed",
      "Warranty": "10 years",
    },
    isActive: true,
    isFeatured: false,
    requiresInstallation: false,
    rating: 4,
    reviewCount: 22,
    createdAt: new Date("2026-02-10"),
    updatedAt: new Date("2026-03-15"),
  },
  {
    id: "p9",
    name: "7.5KVA Hybrid Inverter",
    slug: "7-5kva-hybrid-inverter",
    description: "The sweet spot for larger homes and small businesses. Handles heavy appliances including air conditioners and pumps. Built-in WiFi monitoring lets you track your system from anywhere.",
    shortDescription: "Large home & SME grade · WiFi monitoring · AC ready",
    price: 520000,
    stockQuantity: 6,
    lowStockThreshold: 2,
    category: "inverters",
    brand: "Olea Select",
    images: [],
    specifications: {
      "Rated Power": "7.5KVA / 6,000W",
      "Input Voltage": "48V DC",
      "Output Voltage": "220V AC ±3%",
      "Solar Input": "Up to 7,500W",
      "Max Battery Voltage": "60V",
      "Efficiency": "≥95%",
      "Monitoring": "WiFi app (iOS & Android)",
      "Waveform": "Pure Sine Wave",
      "Warranty": "2 years",
    },
    isActive: true,
    isFeatured: false,
    requiresInstallation: true,
    rating: 5,
    reviewCount: 14,
    createdAt: new Date("2026-02-15"),
    updatedAt: new Date("2026-03-15"),
  },
  {
    id: "p10",
    name: "100Ah LiFePO4 Battery",
    slug: "100ah-lifepo4-battery",
    description: "Compact lithium iron phosphate battery ideal for smaller homes and backup systems. Built-in BMS ensures safety and longevity across 6,000+ charge cycles.",
    shortDescription: "LiFePO4 · 5.12kWh · 6,000+ cycles · BMS included",
    price: 340000,
    stockQuantity: 15,
    lowStockThreshold: 3,
    category: "batteries",
    brand: "Olea Select",
    images: [],
    specifications: {
      "Capacity": "100Ah / 5.12kWh",
      "Chemistry": "LiFePO4",
      "Nominal Voltage": "51.2V",
      "Cycle Life": "6,000+ cycles",
      "Max Charge Current": "50A",
      "Weight": "26kg",
      "Warranty": "3 years",
    },
    isActive: true,
    isFeatured: false,
    requiresInstallation: false,
    rating: 5,
    reviewCount: 18,
    createdAt: new Date("2026-03-01"),
    updatedAt: new Date("2026-03-15"),
  },
  {
    id: "p11",
    name: "2KVA Hybrid Inverter",
    slug: "2kva-hybrid-inverter",
    description: "Entry-level hybrid inverter for small apartments and starter solar setups. Handles lights, fans, TV, and small appliances with pure sine wave output.",
    shortDescription: "Entry-level · pure sine wave · solar-ready",
    price: 120000,
    stockQuantity: 20,
    lowStockThreshold: 5,
    category: "inverters",
    brand: "Olea Select",
    images: [],
    specifications: {
      "Rated Power": "2KVA / 1,600W",
      "Input Voltage": "24V DC",
      "Output Voltage": "220V AC ±5%",
      "Solar Input": "Up to 1,500W",
      "Waveform": "Pure Sine Wave",
      "Warranty": "1 year",
    },
    isActive: true,
    isFeatured: false,
    requiresInstallation: true,
    rating: 4,
    reviewCount: 35,
    createdAt: new Date("2026-03-01"),
    updatedAt: new Date("2026-03-15"),
  },
  {
    id: "p12",
    name: "Solar DC Cable 6mm² (10m)",
    slug: "solar-dc-cable-6mm",
    description: "UV-resistant, double-insulated solar DC cable rated for outdoor use. TÜV certified for solar installations. Sold in 10m rolls, red + black pair.",
    shortDescription: "UV-resistant · TÜV certified · 10m roll · red + black pair",
    price: 28000,
    stockQuantity: 100,
    lowStockThreshold: 20,
    category: "accessories",
    brand: "Olea Select",
    images: [],
    specifications: {
      "Cross-section": "6mm²",
      "Voltage Rating": "1500V DC",
      "Temperature": "-40°C to +90°C",
      "Insulation": "Double XLPE",
      "Length": "10m (per roll)",
      "Certification": "TÜV / IEC 62930",
    },
    isActive: true,
    isFeatured: false,
    requiresInstallation: false,
    rating: 4,
    reviewCount: 49,
    createdAt: new Date("2026-03-05"),
    updatedAt: new Date("2026-03-15"),
  },
  {
    id: "p13",
    name: "500W Premium Mono Panel",
    slug: "500w-premium-mono-panel",
    description: "High-output half-cut cell monocrystalline panel with better shade tolerance and higher efficiency. Ideal for space-constrained rooftops that need maximum output.",
    shortDescription: "Half-cut cell · 21.8% efficiency · shade tolerant",
    price: 130000,
    compareAtPrice: 148000,
    stockQuantity: 12,
    lowStockThreshold: 3,
    category: "solar_panels",
    brand: "Olea Select",
    images: [],
    specifications: {
      "Peak Power": "500W",
      "Cell Type": "Monocrystalline Half-Cut",
      "Efficiency": "21.8%",
      "Open Circuit Voltage": "53.4V",
      "Dimensions": "2278 × 1134 × 35mm",
      "Weight": "28.5kg",
      "Warranty": "25 years performance",
    },
    isActive: true,
    isFeatured: false,
    requiresInstallation: false,
    rating: 5,
    reviewCount: 12,
    createdAt: new Date("2026-03-05"),
    updatedAt: new Date("2026-03-15"),
  },
  {
    id: "p14",
    name: "40A MPPT Charge Controller",
    slug: "40a-mppt-charge-controller",
    description: "Compact MPPT controller for small to mid-size home systems. Bluetooth connectivity for real-time monitoring via mobile app. Compatible with lithium and lead-acid batteries.",
    shortDescription: "MPPT · Bluetooth monitoring · 12/24/48V auto",
    price: 52000,
    stockQuantity: 25,
    lowStockThreshold: 5,
    category: "charge_controllers",
    brand: "Olea Select",
    images: [],
    specifications: {
      "Rated Current": "40A",
      "Max PV Open Circuit": "100V",
      "Battery Voltage": "12/24/48V auto",
      "Efficiency": "≥98%",
      "Display": "Bluetooth app + LED",
      "Warranty": "1 year",
    },
    isActive: true,
    isFeatured: false,
    requiresInstallation: false,
    rating: 4,
    reviewCount: 27,
    createdAt: new Date("2026-03-10"),
    updatedAt: new Date("2026-03-15"),
  },
  {
    id: "p15",
    name: "Smart WiFi Energy Monitor",
    slug: "smart-wifi-energy-monitor",
    description: "Non-invasive energy monitor that gives real-time consumption data via app. Supports alerts, usage history, and remote notifications for any home or business system.",
    shortDescription: "Real-time monitoring · WiFi + app · usage alerts",
    price: 45000,
    stockQuantity: 30,
    lowStockThreshold: 5,
    category: "accessories",
    brand: "Olea Select",
    images: [],
    specifications: {
      "Connectivity": "WiFi 2.4GHz",
      "Compatibility": "Single and three-phase",
      "App": "iOS + Android",
      "Data History": "12 months",
      "Alerts": "Email + push notifications",
      "Warranty": "1 year",
    },
    isActive: true,
    isFeatured: false,
    requiresInstallation: false,
    rating: 5,
    reviewCount: 41,
    createdAt: new Date("2026-03-10"),
    updatedAt: new Date("2026-03-15"),
  },
  {
    id: "p16",
    name: "15KVA Three-Phase Inverter",
    slug: "15kva-three-phase-inverter",
    description: "Heavy-duty three-phase inverter for large industrial facilities, cold rooms, and commercial buildings. Handles compressors, lifts, and heavy motor loads. Remote monitoring via web portal and RS485.",
    shortDescription: "Three-phase · 15KVA · industrial grade · web portal",
    price: 1800000,
    stockQuantity: 1,
    lowStockThreshold: 1,
    category: "inverters",
    brand: "Olea Select",
    images: [],
    specifications: {
      "Rated Power": "15KVA / 12,000W",
      "Phase": "Three-phase output",
      "Output Voltage": "380V AC (3-phase)",
      "Solar Input": "Up to 15,000W",
      "Communication": "WiFi + RS485 + Web portal",
      "Efficiency": "≥95%",
      "Warranty": "2 years",
    },
    isActive: true,
    isFeatured: false,
    requiresInstallation: true,
    rating: 5,
    reviewCount: 3,
    createdAt: new Date("2026-03-15"),
    updatedAt: new Date("2026-03-15"),
  },
  {
    id: "p17",
    name: "5KVA Business Solar System",
    slug: "5kva-business-solar-system",
    description: "Professionally installed solar system for small offices and retail outlets. Includes 5KVA hybrid inverter, 6 × 450W solar panels, 2 × 100Ah LiFePO4 batteries, and full installation by Olea engineers.",
    shortDescription: "Office & retail grade · full installation included · WiFi app",
    price: 1100000,
    stockQuantity: 4,
    lowStockThreshold: 1,
    category: "systems",
    brand: "Olea Technologies",
    images: [],
    specifications: {
      "Inverter": "5KVA Hybrid",
      "Solar Panels": "6 × 450W",
      "Battery": "2 × 100Ah LiFePO4",
      "Total Solar": "2,700W",
      "Battery Storage": "10.24kWh",
      "Daily Output": "~8–12kWh",
      "Installation": "Included",
      "Monitoring": "WiFi app included",
      "Warranty": "System: 2yr / Panels: 25yr",
    },
    isActive: true,
    isFeatured: true,
    requiresInstallation: true,
    rating: 5,
    reviewCount: 8,
    createdAt: new Date("2026-03-15"),
    updatedAt: new Date("2026-03-15"),
  },
  {
    id: "p18",
    name: "150Ah Sealed AGM Battery",
    slug: "150ah-sealed-agm-battery",
    description: "Maintenance-free sealed lead-acid battery for budget-conscious residential and backup installations. No water top-up required. Good choice for starter systems before upgrading to lithium.",
    shortDescription: "Maintenance-free · sealed · 7.68kWh · budget pick",
    price: 85000,
    stockQuantity: 22,
    lowStockThreshold: 5,
    category: "batteries",
    brand: "Olea Select",
    images: [],
    specifications: {
      "Capacity": "150Ah / 7.68kWh",
      "Chemistry": "Sealed AGM",
      "Nominal Voltage": "51.2V",
      "Cycle Life": "500+ cycles",
      "Weight": "36kg",
      "Warranty": "1 year",
    },
    isActive: true,
    isFeatured: false,
    requiresInstallation: false,
    rating: 3,
    reviewCount: 44,
    createdAt: new Date("2026-04-01"),
    updatedAt: new Date("2026-04-01"),
  },
  {
    id: "p19",
    name: "3KVA Hybrid Inverter",
    slug: "3kva-hybrid-inverter",
    description: "Mid-range hybrid inverter suited for 2–3 bedroom homes. Runs fans, lights, TV, fridge, and small AC units. Auto-switches between solar, battery, and grid with zero transfer delay.",
    shortDescription: "2–3 bed home · zero transfer delay · solar + grid",
    price: 165000,
    stockQuantity: 14,
    lowStockThreshold: 3,
    category: "inverters",
    brand: "Olea Select",
    images: [],
    specifications: {
      "Rated Power": "3KVA / 2,400W",
      "Input Voltage": "48V DC",
      "Output Voltage": "220V AC ±5%",
      "Solar Input": "Up to 3,000W",
      "Waveform": "Pure Sine Wave",
      "Warranty": "2 years",
    },
    isActive: true,
    isFeatured: false,
    requiresInstallation: true,
    rating: 4,
    reviewCount: 20,
    createdAt: new Date("2026-04-01"),
    updatedAt: new Date("2026-04-01"),
  },
  {
    id: "p20",
    name: "600W High-Power Mono Panel",
    slug: "600w-high-power-mono-panel",
    description: "Large-format 600W panel for commercial rooftops and ground-mounted arrays. Half-cut cell design reduces hot-spot losses. Fewer panels needed per system saves mounting hardware and labour.",
    shortDescription: "Large format · half-cut · 22.1% efficiency",
    price: 155000,
    compareAtPrice: 172000,
    stockQuantity: 8,
    lowStockThreshold: 2,
    category: "solar_panels",
    brand: "Olea Select",
    images: [],
    specifications: {
      "Peak Power": "600W",
      "Cell Type": "Mono Half-Cut",
      "Efficiency": "22.1%",
      "Open Circuit Voltage": "57.8V",
      "Dimensions": "2465 × 1134 × 35mm",
      "Weight": "32kg",
      "Warranty": "25 years performance",
    },
    isActive: true,
    isFeatured: false,
    requiresInstallation: false,
    rating: 5,
    reviewCount: 6,
    createdAt: new Date("2026-04-01"),
    updatedAt: new Date("2026-04-01"),
  },
  {
    id: "p21",
    name: "30A PWM Charge Controller",
    slug: "30a-pwm-charge-controller",
    description: "Simple and reliable PWM controller for small standalone solar setups, water pumping systems, and rural off-grid applications. LCD display shows battery status at a glance.",
    shortDescription: "Budget-friendly · 30A · LCD · 12/24V auto",
    price: 18500,
    stockQuantity: 40,
    lowStockThreshold: 10,
    category: "charge_controllers",
    brand: "Olea Select",
    images: [],
    specifications: {
      "Rated Current": "30A",
      "Battery Voltage": "12/24V auto",
      "Load Current": "30A",
      "Display": "LCD",
      "Warranty": "1 year",
    },
    isActive: true,
    isFeatured: false,
    requiresInstallation: false,
    rating: 4,
    reviewCount: 73,
    createdAt: new Date("2026-04-05"),
    updatedAt: new Date("2026-04-05"),
  },
  {
    id: "p22",
    name: "MC4 Connector Kit (10 Pairs)",
    slug: "mc4-connector-kit-10-pairs",
    description: "Industry-standard MC4 solar connectors for secure, weatherproof panel-to-cable connections. UV and corrosion-resistant housing rated for 30 years outdoor use. Includes 2 Y-branch connectors.",
    shortDescription: "10 pairs + 2 Y-connectors · IP68 · 30yr rated",
    price: 8500,
    stockQuantity: 200,
    lowStockThreshold: 30,
    category: "accessories",
    brand: "Olea Select",
    images: [],
    specifications: {
      "Quantity": "10 male + 10 female pairs",
      "Current Rating": "30A",
      "Voltage Rating": "1000V DC",
      "Protection": "IP68",
      "Material": "UV-resistant ABS",
      "Includes": "2 × Y-branch connectors",
    },
    isActive: true,
    isFeatured: false,
    requiresInstallation: false,
    rating: 4,
    reviewCount: 88,
    createdAt: new Date("2026-04-05"),
    updatedAt: new Date("2026-04-05"),
  },
  {
    id: "p23",
    name: "Surge Protection Device",
    slug: "surge-protection-device",
    description: "Combined AC/DC surge protection module for residential and commercial solar installations. Guards inverters, charge controllers, and loads against lightning-induced surges and voltage spikes.",
    shortDescription: "AC + DC protection · DIN rail mount · 20kA",
    price: 22000,
    stockQuantity: 35,
    lowStockThreshold: 8,
    category: "accessories",
    brand: "Olea Select",
    images: [],
    specifications: {
      "Protection Type": "AC + DC combined",
      "Max Surge Current": "20kA",
      "Voltage Range": "Up to 420V AC / 1000V DC",
      "Mounting": "DIN rail",
      "Warranty": "1 year",
    },
    isActive: true,
    isFeatured: false,
    requiresInstallation: false,
    rating: 5,
    reviewCount: 29,
    createdAt: new Date("2026-04-10"),
    updatedAt: new Date("2026-04-10"),
  },
  {
    id: "p24",
    name: "10KVA Complete Home System",
    slug: "10kva-complete-home-system",
    description: "Our premium residential package for large 4–5 bedroom homes. Powers everything — ACs, fridge, washing machine, lights, and more. Professionally installed with 5-year support contract.",
    shortDescription: "4–5 bed home · full installation · 5yr support",
    price: 1950000,
    stockQuantity: 2,
    lowStockThreshold: 1,
    category: "systems",
    brand: "Olea Technologies",
    images: [],
    specifications: {
      "Inverter": "10KVA Hybrid",
      "Solar Panels": "12 × 450W",
      "Battery": "4 × 200Ah LiFePO4",
      "Total Solar": "5,400W",
      "Battery Storage": "40.96kWh",
      "Daily Output": "~24–30kWh",
      "Installation": "Included",
      "Support": "5-year service contract",
      "Warranty": "System: 2yr / Panels: 25yr",
    },
    isActive: true,
    isFeatured: true,
    requiresInstallation: true,
    rating: 5,
    reviewCount: 5,
    createdAt: new Date("2026-04-10"),
    updatedAt: new Date("2026-04-10"),
  },
  {
    id: "p25",
    name: "Solar Roof Cable Trunking (5m)",
    slug: "solar-roof-cable-trunking",
    description: "UV-resistant PVC cable trunking to protect DC cables on rooftop installations. Snap-lid design for easy access. Includes mounting clips and end caps.",
    shortDescription: "UV-resistant · snap-lid · 5m with clips + end caps",
    price: 15000,
    stockQuantity: 60,
    lowStockThreshold: 15,
    category: "accessories",
    brand: "Olea Select",
    images: [],
    specifications: {
      "Length": "5m per set",
      "Channel Size": "40 × 25mm",
      "Material": "UV-resistant PVC",
      "Colour": "White or Grey",
      "Includes": "Mounting clips + end caps",
      "Warranty": "1 year",
    },
    isActive: true,
    isFeatured: false,
    requiresInstallation: false,
    rating: 4,
    reviewCount: 37,
    createdAt: new Date("2026-04-15"),
    updatedAt: new Date("2026-04-15"),
  },
  {
    id: "p26",
    name: "4KVA Off-Grid Inverter",
    slug: "4kva-off-grid-inverter",
    description: "Pure off-grid inverter for remote cabins, farms, and sites without grid access. Simple battery-only input with solar MPPT charging built in. Rugged design handles generator-quality input.",
    shortDescription: "Off-grid · battery + solar input · MPPT built-in",
    price: 195000,
    stockQuantity: 9,
    lowStockThreshold: 2,
    category: "inverters",
    brand: "Olea Select",
    images: [],
    specifications: {
      "Rated Power": "4KVA / 3,200W",
      "Battery Input": "48V DC",
      "Solar MPPT": "Built-in, up to 4,000W",
      "Output": "220V AC pure sine wave",
      "Efficiency": "≥92%",
      "Warranty": "2 years",
    },
    isActive: true,
    isFeatured: false,
    requiresInstallation: true,
    rating: 4,
    reviewCount: 11,
    createdAt: new Date("2026-04-15"),
    updatedAt: new Date("2026-04-15"),
  },
  {
    id: "p27",
    name: "250W Compact Mono Panel",
    slug: "250w-compact-mono-panel",
    description: "Compact monocrystalline panel perfect for balcony, carport, and small rooftop installations. Lightweight frame and smaller footprint. Ideal for supplementing generator or adding to small battery systems.",
    shortDescription: "Compact · 20.5% efficiency · lightweight",
    price: 58000,
    stockQuantity: 30,
    lowStockThreshold: 8,
    category: "solar_panels",
    brand: "Olea Select",
    images: [],
    specifications: {
      "Peak Power": "250W",
      "Cell Type": "Monocrystalline",
      "Efficiency": "20.5%",
      "Dimensions": "1640 × 992 × 35mm",
      "Weight": "14kg",
      "Warranty": "10 years performance",
    },
    isActive: true,
    isFeatured: false,
    requiresInstallation: false,
    rating: 4,
    reviewCount: 19,
    createdAt: new Date("2026-04-15"),
    updatedAt: new Date("2026-04-15"),
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return SEED_PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  return SEED_PRODUCTS.filter((p) => p.category === category && p.isActive);
}

export function getFeaturedProducts(): Product[] {
  return SEED_PRODUCTS.filter((p) => p.isFeatured && p.isActive);
}
