import type { Product } from "@/types";

export const SEED_PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "5KVA Hybrid Inverter",
    slug: "5kva-hybrid-inverter",
    description: "A high-performance hybrid inverter designed for Nigerian conditions. Handles both grid and battery power with seamless switching. Supports solar input up to 5,000W and delivers pure sine wave output suitable for sensitive electronics.",
    shortDescription: "Pure sine wave · grid + battery · solar ready",
    price: 280000,
    compareAtPrice: 320000,
    stockQuantity: 12,
    lowStockThreshold: 3,
    category: "inverters",
    brand: "Olea Select",
    images: [],
    specifications: {
      "Rated Power": "5KVA / 4,000W",
      "Input Voltage": "48V DC",
      "Output Voltage": "220V AC ±5%",
      "Battery Type": "Lithium / Lead-Acid",
      "Solar Input": "Up to 5,000W",
      "Efficiency": "≥93%",
      "Waveform": "Pure Sine Wave",
      "Dimensions": "560 × 290 × 155mm",
      "Weight": "18kg",
      "Warranty": "2 years",
    },
    isActive: true,
    isFeatured: true,
    requiresInstallation: true,
    rating: 5,
    reviewCount: 42,
    createdAt: new Date("2026-01-10"),
    updatedAt: new Date("2026-03-15"),
  },
  {
    id: "p2",
    name: "450W Mono Solar Panel",
    slug: "450w-mono-solar-panel",
    description: "Tier-1 monocrystalline solar panel with 25-year performance warranty. High efficiency cells deliver maximum output even in diffuse light — ideal for Lagos, Abuja, and the broader Nigerian climate.",
    shortDescription: "Tier-1 monocrystalline · 25yr warranty · high efficiency",
    price: 95000,
    stockQuantity: 4,
    lowStockThreshold: 5,
    category: "solar_panels",
    brand: "Olea Select",
    images: [],
    specifications: {
      "Peak Power": "450W",
      "Cell Type": "Monocrystalline PERC",
      "Efficiency": "21.3%",
      "Open Circuit Voltage": "49.2V",
      "Short Circuit Current": "11.6A",
      "Operating Temperature": "-40°C to +85°C",
      "Dimensions": "2094 × 1038 × 35mm",
      "Weight": "21.5kg",
      "Warranty": "25 years performance",
    },
    isActive: true,
    isFeatured: true,
    requiresInstallation: false,
    rating: 4,
    reviewCount: 28,
    createdAt: new Date("2026-01-10"),
    updatedAt: new Date("2026-03-15"),
  },
  {
    id: "p3",
    name: "200Ah Lithium Battery",
    slug: "200ah-lithium-battery",
    description: "LiFePO4 lithium battery with 6,000+ cycle life — that's 15–20 years of daily use. Built-in BMS protects against overcharge, over-discharge, and short circuits. The smartest long-term investment in your energy system.",
    shortDescription: "LiFePO4 · 6,000+ cycles · built-in BMS",
    price: 620000,
    stockQuantity: 8,
    lowStockThreshold: 2,
    category: "batteries",
    brand: "Olea Select",
    images: [],
    specifications: {
      "Capacity": "200Ah / 10.24kWh",
      "Chemistry": "LiFePO4",
      "Nominal Voltage": "51.2V",
      "Cycle Life": "6,000+ cycles",
      "Charge Voltage": "58.4V",
      "Max Charge Current": "100A",
      "Max Discharge Current": "200A",
      "Operating Temp": "0°C to +55°C",
      "Weight": "48kg",
      "Warranty": "5 years",
    },
    isActive: true,
    isFeatured: true,
    requiresInstallation: false,
    rating: 5,
    reviewCount: 61,
    createdAt: new Date("2026-01-10"),
    updatedAt: new Date("2026-03-15"),
  },
  {
    id: "p4",
    name: "3.5KVA Complete Home System",
    slug: "3-5kva-complete-home-system",
    description: "Everything you need to power a 3–4 bedroom home, professionally installed by our engineers. Includes hybrid inverter, solar panels, lithium batteries, mounting hardware, wiring, and commissioning. One price. Zero stress.",
    shortDescription: "Complete home kit · installation included · monitored",
    price: 1450000,
    stockQuantity: 3,
    lowStockThreshold: 1,
    category: "systems",
    brand: "Olea Technologies",
    images: [],
    specifications: {
      "Inverter": "3.5KVA Hybrid",
      "Solar Panels": "6 × 450W",
      "Battery": "2 × 200Ah LiFePO4",
      "Total Solar": "2,700W",
      "Battery Storage": "20.48kWh",
      "Daily Output": "~12–16kWh",
      "Installation": "Included",
      "Monitoring": "WiFi app included",
      "Warranty": "System: 2yr / Panels: 25yr",
    },
    isActive: true,
    isFeatured: true,
    requiresInstallation: true,
    rating: 5,
    reviewCount: 19,
    createdAt: new Date("2026-01-10"),
    updatedAt: new Date("2026-03-15"),
  },
  {
    id: "p5",
    name: "MPPT 60A Charge Controller",
    slug: "mppt-60a-charge-controller",
    description: "Maximum Power Point Tracking controller that squeezes every watt from your panels. Up to 30% more efficient than PWM controllers. Compatible with 12V, 24V, and 48V battery banks.",
    shortDescription: "Max power point tracking · 12/24/48V · LCD display",
    price: 78000,
    stockQuantity: 20,
    lowStockThreshold: 5,
    category: "charge_controllers",
    brand: "Olea Select",
    images: [],
    specifications: {
      "Rated Current": "60A",
      "Max PV Open Circuit": "150V",
      "Battery Voltage": "12/24/48V auto",
      "Max PV Input Power": "780W (12V) / 1560W (24V) / 3120W (48V)",
      "Efficiency": "≥98%",
      "Display": "LCD backlit",
      "Dimensions": "165 × 112 × 52mm",
      "Weight": "0.78kg",
      "Warranty": "1 year",
    },
    isActive: true,
    isFeatured: false,
    requiresInstallation: false,
    rating: 4,
    reviewCount: 33,
    createdAt: new Date("2026-02-01"),
    updatedAt: new Date("2026-03-15"),
  },
  {
    id: "p6",
    name: "10KVA Industrial Inverter",
    slug: "10kva-industrial-inverter",
    description: "Three-phase industrial grade inverter built for factories, warehouses, and commercial facilities. Handles heavy motor loads with ease. Remote monitoring via WiFi and RS485.",
    shortDescription: "Three-phase · factory grade · WiFi monitoring",
    price: 980000,
    stockQuantity: 2,
    lowStockThreshold: 1,
    category: "inverters",
    brand: "Olea Select",
    images: [],
    specifications: {
      "Rated Power": "10KVA / 8,000W",
      "Phase": "Three-phase output",
      "Input Voltage": "192V DC (4 × 48V)",
      "Output Voltage": "380V AC (3-phase)",
      "Solar Input": "Up to 10,000W",
      "Efficiency": "≥94%",
      "Waveform": "Pure Sine Wave",
      "Communication": "WiFi + RS485",
      "Warranty": "2 years",
    },
    isActive: true,
    isFeatured: false,
    requiresInstallation: true,
    rating: 5,
    reviewCount: 7,
    createdAt: new Date("2026-02-01"),
    updatedAt: new Date("2026-03-15"),
  },
  {
    id: "p7",
    name: "300W Poly Solar Panel",
    slug: "300w-poly-solar-panel",
    description: "Reliable polycrystalline panel for budget-conscious installations. A solid performer for rural and off-grid setups where cost per watt matters more than footprint.",
    shortDescription: "Budget-friendly · reliable · off-grid ready",
    price: 62000,
    stockQuantity: 0,
    lowStockThreshold: 5,
    category: "solar_panels",
    brand: "Olea Select",
    images: [],
    specifications: {
      "Peak Power": "300W",
      "Cell Type": "Polycrystalline",
      "Efficiency": "16.5%",
      "Open Circuit Voltage": "45.8V",
      "Dimensions": "1956 × 992 × 40mm",
      "Weight": "18kg",
      "Warranty": "10 years performance",
    },
    isActive: true,
    isFeatured: false,
    requiresInstallation: false,
    rating: 4,
    reviewCount: 15,
    createdAt: new Date("2026-02-10"),
    updatedAt: new Date("2026-03-15"),
  },
  {
    id: "p8",
    name: "Aluminum Mounting Rail Kit",
    slug: "aluminum-mounting-rail-kit",
    description: "Heavy-duty aluminum mounting rails for rooftop solar panel installation. Corrosion-resistant, pre-drilled, compatible with all standard panel sizes. Includes mid and end clamps.",
    shortDescription: "Aluminum · 6m × 4 rails · clamps included",
    price: 35000,
    stockQuantity: 50,
    lowStockThreshold: 10,
    category: "accessories",
    brand: "Olea Select",
    images: [],
    specifications: {
      "Material": "Anodized Aluminum",
      "Rail Length": "6m per rail",
      "Quantity": "4 rails per set",
      "Compatible": "All standard panels",
      "Includes": "Mid clamps, end clamps, T-bolts",
      "Load Rating": "Up to 480kg distributed",
      "Warranty": "10 years",
    },
    isActive: true,
    isFeatured: false,
    requiresInstallation: false,
    rating: 4,
    reviewCount: 22,
    createdAt: new Date("2026-02-10"),
    updatedAt: new Date("2026-03-15"),
  },
  {
    id: "p9",
    name: "7.5KVA Hybrid Inverter",
    slug: "7-5kva-hybrid-inverter",
    description: "The sweet spot for larger homes and small businesses. Handles heavy appliances including air conditioners and pumps. Built-in WiFi monitoring lets you track your system from anywhere.",
    shortDescription: "Large home & SME grade · WiFi monitoring · AC ready",
    price: 520000,
    stockQuantity: 6,
    lowStockThreshold: 2,
    category: "inverters",
    brand: "Olea Select",
    images: [],
    specifications: {
      "Rated Power": "7.5KVA / 6,000W",
      "Input Voltage": "48V DC",
      "Output Voltage": "220V AC ±3%",
      "Solar Input": "Up to 7,500W",
      "Max Battery Voltage": "60V",
      "Efficiency": "≥95%",
      "Monitoring": "WiFi app (iOS & Android)",
      "Waveform": "Pure Sine Wave",
      "Warranty": "2 years",
    },
    isActive: true,
    isFeatured: false,
    requiresInstallation: true,
    rating: 5,
    reviewCount: 14,
    createdAt: new Date("2026-02-15"),
    updatedAt: new Date("2026-03-15"),
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return SEED_PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  return SEED_PRODUCTS.filter((p) => p.category === category && p.isActive);
}

export function getFeaturedProducts(): Product[] {
  return SEED_PRODUCTS.filter((p) => p.isFeatured && p.isActive);
}
